Improve reliability
1. Perform operations relative to the current directory.
2. Make sure file ownership is correct.
3. Ignore readdir races.

diff --git a/btrfs-snapshot b/btrfs-snapshot
--- a/btrfs-snapshot
+++ b/btrfs-snapshot
@@ -1,15 +1,6 @@
 #!/bin/bash
-set -e
+set -eu
 shopt -s nullglob
-
-subvol="$1"
-backup_dir="${2:-${subvol}/.backups}"
-ignore_file="${subvol}/.backupignore"
-lock_file="${backup_dir}/lock"
-date="$(date -u +%FT%T)"
-today_dir="${backup_dir}/${date}"
-temp_dir="${backup_dir}/temp-${date}"
-current_dir="${backup_dir}/current"
 
 err() {
     local ret=$?
@@ -20,10 +11,34 @@ err() {
     return $ret
 }
 
+[[ "$#" -eq 1 ]] || err "Must be called with exactly one argument: the subvolume to snapshot."
+
+backup_dir="./.backups"
+ignore_file="./.backupignore"
+lock_file="${backup_dir}/lock"
+date="$(date -u +%FT%T)"
+today_dir="${backup_dir}/${date}"
+temp_dir="${backup_dir}/temp-${date}"
+current_dir="${backup_dir}/current"
+
+identity="$(id -u)-$(id -g)"
+check_owner() {
+    local id mode
+    read -r id mode < <(stat -c "%u-%g %#a")
+    # We must own it, and nobody else can write (and no sticky!)
+    [[ "$id" == "$identity" ]] && [[ $(( "$mode" & !0755 )) -eq 0 ]]
+}
+
 # Setup
-cd /
-test -d "${subvol}" || err "No such directory: ${subvol}"
-test -d "${backup_dir}" || btrfs subvolume create -p "${backup_dir}"
+
+# Make sure the backup volume exists and that we're the owner.
+# We CD into it to avoid TOCTOU issues.
+cd "$1" || err "Failed to change directory into the subvolume: $1"
+check_owner "." || err "Refusing to snapshot a directory we don't own."
+
+# Check the backups directory.
+test -d "${backup_dir}" || btrfs subvolume create "${backup_dir}"
+check_owner "${backup_dir}" || err "Refusing use a backup dir we don't own."
 chmod 0700 "${backup_dir}"
 
 # Lock
@@ -37,15 +52,22 @@ if [[ ${#stale_temp} -gt 0 ]]; then
 fi
 
 # Snapshot
-btrfs subvolume snapshot "${subvol}" "${temp_dir}"
+btrfs subvolume snapshot . "${temp_dir}"
 
 # Cleanup snapshot
+pushd "${temp_dir}"
+
+# Read the ignore file from the snapshot itself.
 if [[ -e "${ignore_file}" ]]; then
-    while read -r fname; do
-        target="${temp_dir:?}/${fname}"
-        [[ -e "${target}" ]] || continue
-        rm -rf -- "${target}"
-    done < "${ignore_file}"
+    if ! check_owner "${ignore_file}"; then
+        echo "Refusing to use an ignore file we don't own, skipping."
+    else
+        while read -r fname; do
+            target="./${fname}"
+            [[ -e "${target}" ]] || continue
+            rm -rf -- "${target}"
+        done < "${ignore_file}"
+    fi
 fi
 
 # NOTE: Deleting files with find is simply racy no matter what. So I pipe to xargs.
@@ -53,12 +75,14 @@ fi
 # No we can't use -execdir. Even with -depth, it still races.
 
 # Clean ignored files (build artifacts, etc.).
-find "${temp_dir:?}" -mount -depth -type d -name .git -printf '%h\0' \
-     | xargs -r -0 -I '{}' git -C '{}' clean -Xqfd || true
+find . -ignore_readdir_race -mount -depth -type d -name .git -printf '%h\0' \
+     | xargs -r -0 -I '{}' git -C '{}' clean -Xqfd
 
-# Remove all cache directories, but don't descend into .git directories.
-find "${temp_dir:?}" -mount -depth -type f -name CACHEDIR.TAG -printf '%h\0' \
-    | xargs -r -0 rm --one-file-system -rf -- || true
+# Remove all cache directories.
+find . -ignore_readdir_race -mount -depth -type f -name CACHEDIR.TAG -printf '%h\0' \
+    | xargs -r -0 rm --one-file-system -rf --
+
+popd
 
 # Finish it
 btrfs property set -ts "${temp_dir}" ro true
